### ISSUE TITLE
Typos in Create User Post requests

### ISSUE THREAD

**Issue by dpatil-fw** [FIWARE/tutorials.Identity-Management#6]
The users manager1 and detective1 are created twice via POST requests, second example should have manager2 and detective2
 
It is below this line:
_For example to create additional accounts for Bob, the Regional Manager, Charlie, the Head of Security and their direct reports_

These are the requests:

curl -iX POST \
  'http://localhost:3005/v1/users' \
  -H 'Content-Type: application/json' \
  -H 'X-Auth-token: {{X-Auth-token}}' \
  -d '{
  "user": {
    "username": "manager1",
    "email": "manager1@test.com",
    "password": "test"
  }
}'

curl -iX POST \
  'http://localhost:3005/v1/users' \
  -H 'Content-Type: application/json' \
  -H 'X-Auth-token: {{X-Auth-token}}' \
  -d '{
  "user": {
    "username": "detective1",
    "email": "detective1@test.com",
    "password": "test"
  }
}'

**Comment by jason-fox** [comment]
Fixed f2ecce5
